<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2024-06-06T12:48:45-05:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      disabled
 * @group     settings
 * @namespace msv_cookie_consent
 * -----------------------------------------------------------------------------
 */
return [
    'mode' => 'opt-in',
    'theme' => 'auto',
    'modal_layout' => 'box wide',
    'modal_position' => 'bottom center',
    'settings_layout' => 'box',
    'settings_position' => 'left',
    'force_consent' => '',
    'header_tracking_scripts' => '',
    'header_targeting_scripts' => '',
    'footer_tracking_scripts' => '',
    'footer_targeting_scripts' => '',
    'disabled' => '0',
    'text' => [
        'modal_description' => '<p>By using this website, you agree to the use of cookies and other tracking tools. For more information, see our <a href="/privacy-and-security">privacy policy</a>.</p>',
        'modal_title' => 'We, and third parties, use cookies and/or other electronic tools to enhance user experience.',
        'preferences_header_title' => '',
        'preferences_header_description' => '',
        'preferences_footer_title' => '',
        'preferences_footer_description' => '',
    ],
];
