<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2023-12-13T15:55:28+00:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      server_timezone
 * @group     app
 * @namespace null
 * -----------------------------------------------------------------------------
 */
return [
    'server_timezone' => 'America/Chicago',
];
