<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2023-11-13T21:40:28+00:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      categories
 * @group     studio_testimonials_pro
 * @namespace null
 * -----------------------------------------------------------------------------
 */
return [
    'categories' => 'a:1:{i:0;s:21:"Employee Testimonials";}',
];
