<?php

namespace DoctrineProxies\__CG__\Concrete\Package\AccordionPro\Src\Entity;


/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class StylePreset extends \Concrete\Package\AccordionPro\Src\Entity\StylePreset implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     *
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', 'presetId', 'presetName', 'isSystemPreset', 'titleBackgroundColorNormal', 'titleBackgroundColorHover', 'titleBackgroundColorActive', 'titleTextColorNormal', 'titleTextColorHover', 'titleTextColorActive', 'titleTextFontWeight', 'titleTextFontSize', 'titleTextDecoration', 'titleIconNormal', 'titleIconActive', 'titleIconOrientation', 'titleIconPadding', 'titleIconColorNormal', 'titleIconBackgroundColorNormal', 'titleIconColorHover', 'titleIconBackgroundColorHover', 'titleIconColorActive', 'titleIconBackgroundColorActive', 'titleBorderBottomColor', 'titleBorderTopColor', 'titleBorderLeftColor', 'titleBorderRightColor', 'titleBorderBottomWidth', 'titleBorderTopWidth', 'titleBorderLeftWidth', 'titleBorderRightWidth', 'titlePaddingLeft', 'titlePaddingRight', 'titlePaddingBottom', 'titlePaddingTop', 'contentBorderBottomColor', 'contentBorderTopColor', 'contentBorderLeftColor', 'contentBorderRightColor', 'contentBorderBottomWidth', 'contentBorderTopWidth', 'contentBorderLeftWidth', 'contentBorderRightWidth', 'contentPaddingLeft', 'contentPaddingRight', 'contentPaddingBottom', 'contentPaddingTop', 'titleHeight', 'titleLineHeight', 'titleBorderTopStyle', 'titleBorderBottomStyle', 'titleBorderLeftStyle', 'titleBorderRightStyle', 'titleMarginTop', 'titleMarginBottom', 'titleMarginLeft', 'titleMarginRight', 'titleIconMarginTop', 'titleIconMarginBottom', 'titleIconMarginLeft', 'titleIconMarginRight', 'contentBorderTopStyle', 'contentBorderBottomStyle', 'contentBorderLeftStyle', 'contentBorderRightStyle', 'contentMarginTop', 'contentMarginBottom', 'contentMarginLeft', 'contentMarginRight'];
        }

        return ['__isInitialized__', 'presetId', 'presetName', 'isSystemPreset', 'titleBackgroundColorNormal', 'titleBackgroundColorHover', 'titleBackgroundColorActive', 'titleTextColorNormal', 'titleTextColorHover', 'titleTextColorActive', 'titleTextFontWeight', 'titleTextFontSize', 'titleTextDecoration', 'titleIconNormal', 'titleIconActive', 'titleIconOrientation', 'titleIconPadding', 'titleIconColorNormal', 'titleIconBackgroundColorNormal', 'titleIconColorHover', 'titleIconBackgroundColorHover', 'titleIconColorActive', 'titleIconBackgroundColorActive', 'titleBorderBottomColor', 'titleBorderTopColor', 'titleBorderLeftColor', 'titleBorderRightColor', 'titleBorderBottomWidth', 'titleBorderTopWidth', 'titleBorderLeftWidth', 'titleBorderRightWidth', 'titlePaddingLeft', 'titlePaddingRight', 'titlePaddingBottom', 'titlePaddingTop', 'contentBorderBottomColor', 'contentBorderTopColor', 'contentBorderLeftColor', 'contentBorderRightColor', 'contentBorderBottomWidth', 'contentBorderTopWidth', 'contentBorderLeftWidth', 'contentBorderRightWidth', 'contentPaddingLeft', 'contentPaddingRight', 'contentPaddingBottom', 'contentPaddingTop', 'titleHeight', 'titleLineHeight', 'titleBorderTopStyle', 'titleBorderBottomStyle', 'titleBorderLeftStyle', 'titleBorderRightStyle', 'titleMarginTop', 'titleMarginBottom', 'titleMarginLeft', 'titleMarginRight', 'titleIconMarginTop', 'titleIconMarginBottom', 'titleIconMarginLeft', 'titleIconMarginRight', 'contentBorderTopStyle', 'contentBorderBottomStyle', 'contentBorderLeftStyle', 'contentBorderRightStyle', 'contentMarginTop', 'contentMarginBottom', 'contentMarginLeft', 'contentMarginRight'];
    }

    /**
     *
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (StylePreset $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     *
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load(): void
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized(): bool
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized): void
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null): void
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer(): ?\Closure
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null): void
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner(): ?\Closure
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties(): array
    {
        return self::$lazyPropertiesDefaults;
    }


    /**
     * {@inheritDoc}
     */
    public function getPresetId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getPresetId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPresetId', []);

        return parent::getPresetId();
    }

    /**
     * {@inheritDoc}
     */
    public function getPresetName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPresetName', []);

        return parent::getPresetName();
    }

    /**
     * {@inheritDoc}
     */
    public function getIsSystemPreset()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIsSystemPreset', []);

        return parent::getIsSystemPreset();
    }

    /**
     * {@inheritDoc}
     */
    public function getTitleBackgroundColorNormal()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTitleBackgroundColorNormal', []);

        return parent::getTitleBackgroundColorNormal();
    }

    /**
     * {@inheritDoc}
     */
    public function getTitleBackgroundColorHover()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTitleBackgroundColorHover', []);

        return parent::getTitleBackgroundColorHover();
    }

    /**
     * {@inheritDoc}
     */
    public function getTitleBackgroundColorActive()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTitleBackgroundColorActive', []);

        return parent::getTitleBackgroundColorActive();
    }

    /**
     * {@inheritDoc}
     */
    public function getTitleTextColorNormal()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTitleTextColorNormal', []);

        return parent::getTitleTextColorNormal();
    }

    /**
     * {@inheritDoc}
     */
    public function getTitleTextColorHover()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTitleTextColorHover', []);

        return parent::getTitleTextColorHover();
    }

    /**
     * {@inheritDoc}
     */
    public function getTitleTextColorActive()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTitleTextColorActive', []);

        return parent::getTitleTextColorActive();
    }

    /**
     * {@inheritDoc}
     */
    public function getTitleTextFontWeight()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTitleTextFontWeight', []);

        return parent::getTitleTextFontWeight();
    }

    /**
     * {@inheritDoc}
     */
    public function getTitleTextFontSize()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTitleTextFontSize', []);

        return parent::getTitleTextFontSize();
    }

    /**
     * {@inheritDoc}
     */
    public function getTitleTextDecoration()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTitleTextDecoration', []);

        return parent::getTitleTextDecoration();
    }

    /**
     * {@inheritDoc}
     */
    public function getTitleIconNormal()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTitleIconNormal', []);

        return parent::getTitleIconNormal();
    }

    /**
     * {@inheritDoc}
     */
    public function getTitleIconActive()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTitleIconActive', []);

        return parent::getTitleIconActive();
    }

    /**
     * {@inheritDoc}
     */
    public function getTitleIconOrientation()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTitleIconOrientation', []);

        return parent::getTitleIconOrientation();
    }

    /**
     * {@inheritDoc}
     */
    public function getTitleIconPadding()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTitleIconPadding', []);

        return parent::getTitleIconPadding();
    }

    /**
     * {@inheritDoc}
     */
    public function getTitleIconColorNormal()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTitleIconColorNormal', []);

        return parent::getTitleIconColorNormal();
    }

    /**
     * {@inheritDoc}
     */
    public function getTitleIconBackgroundColorNormal()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTitleIconBackgroundColorNormal', []);

        return parent::getTitleIconBackgroundColorNormal();
    }

    /**
     * {@inheritDoc}
     */
    public function getTitleIconColorHover()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTitleIconColorHover', []);

        return parent::getTitleIconColorHover();
    }

    /**
     * {@inheritDoc}
     */
    public function getTitleIconBackgroundColorHover()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTitleIconBackgroundColorHover', []);

        return parent::getTitleIconBackgroundColorHover();
    }

    /**
     * {@inheritDoc}
     */
    public function getTitleIconColorActive()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTitleIconColorActive', []);

        return parent::getTitleIconColorActive();
    }

    /**
     * {@inheritDoc}
     */
    public function getTitleIconBackgroundColorActive()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTitleIconBackgroundColorActive', []);

        return parent::getTitleIconBackgroundColorActive();
    }

    /**
     * {@inheritDoc}
     */
    public function getTitleBorderBottomColor()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTitleBorderBottomColor', []);

        return parent::getTitleBorderBottomColor();
    }

    /**
     * {@inheritDoc}
     */
    public function getTitleBorderTopColor()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTitleBorderTopColor', []);

        return parent::getTitleBorderTopColor();
    }

    /**
     * {@inheritDoc}
     */
    public function getTitleBorderLeftColor()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTitleBorderLeftColor', []);

        return parent::getTitleBorderLeftColor();
    }

    /**
     * {@inheritDoc}
     */
    public function getTitleBorderRightColor()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTitleBorderRightColor', []);

        return parent::getTitleBorderRightColor();
    }

    /**
     * {@inheritDoc}
     */
    public function getTitleBorderBottomWidth()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTitleBorderBottomWidth', []);

        return parent::getTitleBorderBottomWidth();
    }

    /**
     * {@inheritDoc}
     */
    public function getTitleBorderTopWidth()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTitleBorderTopWidth', []);

        return parent::getTitleBorderTopWidth();
    }

    /**
     * {@inheritDoc}
     */
    public function getTitleBorderLeftWidth()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTitleBorderLeftWidth', []);

        return parent::getTitleBorderLeftWidth();
    }

    /**
     * {@inheritDoc}
     */
    public function getTitleBorderRightWidth()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTitleBorderRightWidth', []);

        return parent::getTitleBorderRightWidth();
    }

    /**
     * {@inheritDoc}
     */
    public function getTitlePaddingLeft()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTitlePaddingLeft', []);

        return parent::getTitlePaddingLeft();
    }

    /**
     * {@inheritDoc}
     */
    public function getTitlePaddingRight()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTitlePaddingRight', []);

        return parent::getTitlePaddingRight();
    }

    /**
     * {@inheritDoc}
     */
    public function getTitlePaddingBottom()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTitlePaddingBottom', []);

        return parent::getTitlePaddingBottom();
    }

    /**
     * {@inheritDoc}
     */
    public function getTitlePaddingTop()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTitlePaddingTop', []);

        return parent::getTitlePaddingTop();
    }

    /**
     * {@inheritDoc}
     */
    public function getContentBorderBottomColor()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getContentBorderBottomColor', []);

        return parent::getContentBorderBottomColor();
    }

    /**
     * {@inheritDoc}
     */
    public function getContentBorderTopColor()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getContentBorderTopColor', []);

        return parent::getContentBorderTopColor();
    }

    /**
     * {@inheritDoc}
     */
    public function getContentBorderLeftColor()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getContentBorderLeftColor', []);

        return parent::getContentBorderLeftColor();
    }

    /**
     * {@inheritDoc}
     */
    public function getContentBorderRightColor()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getContentBorderRightColor', []);

        return parent::getContentBorderRightColor();
    }

    /**
     * {@inheritDoc}
     */
    public function getContentBorderBottomWidth()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getContentBorderBottomWidth', []);

        return parent::getContentBorderBottomWidth();
    }

    /**
     * {@inheritDoc}
     */
    public function getContentBorderTopWidth()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getContentBorderTopWidth', []);

        return parent::getContentBorderTopWidth();
    }

    /**
     * {@inheritDoc}
     */
    public function getContentBorderLeftWidth()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getContentBorderLeftWidth', []);

        return parent::getContentBorderLeftWidth();
    }

    /**
     * {@inheritDoc}
     */
    public function getContentBorderRightWidth()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getContentBorderRightWidth', []);

        return parent::getContentBorderRightWidth();
    }

    /**
     * {@inheritDoc}
     */
    public function getContentPaddingLeft()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getContentPaddingLeft', []);

        return parent::getContentPaddingLeft();
    }

    /**
     * {@inheritDoc}
     */
    public function getContentPaddingRight()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getContentPaddingRight', []);

        return parent::getContentPaddingRight();
    }

    /**
     * {@inheritDoc}
     */
    public function getContentPaddingBottom()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getContentPaddingBottom', []);

        return parent::getContentPaddingBottom();
    }

    /**
     * {@inheritDoc}
     */
    public function getContentPaddingTop()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getContentPaddingTop', []);

        return parent::getContentPaddingTop();
    }

    /**
     * {@inheritDoc}
     */
    public function getDefaultTitleHeight()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDefaultTitleHeight', []);

        return parent::getDefaultTitleHeight();
    }

    /**
     * {@inheritDoc}
     */
    public function getDefaultTitleLineHeight()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDefaultTitleLineHeight', []);

        return parent::getDefaultTitleLineHeight();
    }

    /**
     * {@inheritDoc}
     */
    public function getDefaultTitleBorderTopStyle()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDefaultTitleBorderTopStyle', []);

        return parent::getDefaultTitleBorderTopStyle();
    }

    /**
     * {@inheritDoc}
     */
    public function getDefaultTitleBorderBottomStyle()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDefaultTitleBorderBottomStyle', []);

        return parent::getDefaultTitleBorderBottomStyle();
    }

    /**
     * {@inheritDoc}
     */
    public function getDefaultTitleBorderLeftStyle()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDefaultTitleBorderLeftStyle', []);

        return parent::getDefaultTitleBorderLeftStyle();
    }

    /**
     * {@inheritDoc}
     */
    public function getDefaultTitleBorderRightStyle()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDefaultTitleBorderRightStyle', []);

        return parent::getDefaultTitleBorderRightStyle();
    }

    /**
     * {@inheritDoc}
     */
    public function getDefaultTitleMarginTop()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDefaultTitleMarginTop', []);

        return parent::getDefaultTitleMarginTop();
    }

    /**
     * {@inheritDoc}
     */
    public function getDefaultTitleMarginBottom()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDefaultTitleMarginBottom', []);

        return parent::getDefaultTitleMarginBottom();
    }

    /**
     * {@inheritDoc}
     */
    public function getDefaultTitleMarginLeft()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDefaultTitleMarginLeft', []);

        return parent::getDefaultTitleMarginLeft();
    }

    /**
     * {@inheritDoc}
     */
    public function getDefaultTitleMarginRight()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDefaultTitleMarginRight', []);

        return parent::getDefaultTitleMarginRight();
    }

    /**
     * {@inheritDoc}
     */
    public function getDefaultTitleIconMarginTop()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDefaultTitleIconMarginTop', []);

        return parent::getDefaultTitleIconMarginTop();
    }

    /**
     * {@inheritDoc}
     */
    public function getDefaultTitleIconMarginBottom()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDefaultTitleIconMarginBottom', []);

        return parent::getDefaultTitleIconMarginBottom();
    }

    /**
     * {@inheritDoc}
     */
    public function getDefaultTitleIconMarginLeft()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDefaultTitleIconMarginLeft', []);

        return parent::getDefaultTitleIconMarginLeft();
    }

    /**
     * {@inheritDoc}
     */
    public function getDefaultTitleIconMarginRight()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDefaultTitleIconMarginRight', []);

        return parent::getDefaultTitleIconMarginRight();
    }

    /**
     * {@inheritDoc}
     */
    public function getDefaultContentBorderTopStyle()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDefaultContentBorderTopStyle', []);

        return parent::getDefaultContentBorderTopStyle();
    }

    /**
     * {@inheritDoc}
     */
    public function getDefaultContentBorderBottomStyle()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDefaultContentBorderBottomStyle', []);

        return parent::getDefaultContentBorderBottomStyle();
    }

    /**
     * {@inheritDoc}
     */
    public function getDefaultContentBorderLeftStyle()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDefaultContentBorderLeftStyle', []);

        return parent::getDefaultContentBorderLeftStyle();
    }

    /**
     * {@inheritDoc}
     */
    public function getDefaultContentBorderRightStyle()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDefaultContentBorderRightStyle', []);

        return parent::getDefaultContentBorderRightStyle();
    }

    /**
     * {@inheritDoc}
     */
    public function getDefaultContentMarginTop()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDefaultContentMarginTop', []);

        return parent::getDefaultContentMarginTop();
    }

    /**
     * {@inheritDoc}
     */
    public function getDefaultContentMarginBottom()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDefaultContentMarginBottom', []);

        return parent::getDefaultContentMarginBottom();
    }

    /**
     * {@inheritDoc}
     */
    public function getDefaultContentMarginLeft()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDefaultContentMarginLeft', []);

        return parent::getDefaultContentMarginLeft();
    }

    /**
     * {@inheritDoc}
     */
    public function getDefaultContentMarginRight()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDefaultContentMarginRight', []);

        return parent::getDefaultContentMarginRight();
    }

    /**
     * {@inheritDoc}
     */
    public function getTitleHeight()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTitleHeight', []);

        return parent::getTitleHeight();
    }

    /**
     * {@inheritDoc}
     */
    public function getTitleLineHeight()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTitleLineHeight', []);

        return parent::getTitleLineHeight();
    }

    /**
     * {@inheritDoc}
     */
    public function getTitleBorderTopStyle()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTitleBorderTopStyle', []);

        return parent::getTitleBorderTopStyle();
    }

    /**
     * {@inheritDoc}
     */
    public function getTitleBorderBottomStyle()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTitleBorderBottomStyle', []);

        return parent::getTitleBorderBottomStyle();
    }

    /**
     * {@inheritDoc}
     */
    public function getTitleBorderLeftStyle()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTitleBorderLeftStyle', []);

        return parent::getTitleBorderLeftStyle();
    }

    /**
     * {@inheritDoc}
     */
    public function getTitleBorderRightStyle()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTitleBorderRightStyle', []);

        return parent::getTitleBorderRightStyle();
    }

    /**
     * {@inheritDoc}
     */
    public function getTitleMarginTop()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTitleMarginTop', []);

        return parent::getTitleMarginTop();
    }

    /**
     * {@inheritDoc}
     */
    public function getTitleMarginBottom()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTitleMarginBottom', []);

        return parent::getTitleMarginBottom();
    }

    /**
     * {@inheritDoc}
     */
    public function getTitleMarginLeft()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTitleMarginLeft', []);

        return parent::getTitleMarginLeft();
    }

    /**
     * {@inheritDoc}
     */
    public function getTitleMarginRight()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTitleMarginRight', []);

        return parent::getTitleMarginRight();
    }

    /**
     * {@inheritDoc}
     */
    public function getTitleIconMarginTop()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTitleIconMarginTop', []);

        return parent::getTitleIconMarginTop();
    }

    /**
     * {@inheritDoc}
     */
    public function getTitleIconMarginBottom()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTitleIconMarginBottom', []);

        return parent::getTitleIconMarginBottom();
    }

    /**
     * {@inheritDoc}
     */
    public function getTitleIconMarginLeft()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTitleIconMarginLeft', []);

        return parent::getTitleIconMarginLeft();
    }

    /**
     * {@inheritDoc}
     */
    public function getTitleIconMarginRight()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTitleIconMarginRight', []);

        return parent::getTitleIconMarginRight();
    }

    /**
     * {@inheritDoc}
     */
    public function getContentBorderTopStyle()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getContentBorderTopStyle', []);

        return parent::getContentBorderTopStyle();
    }

    /**
     * {@inheritDoc}
     */
    public function getContentBorderBottomStyle()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getContentBorderBottomStyle', []);

        return parent::getContentBorderBottomStyle();
    }

    /**
     * {@inheritDoc}
     */
    public function getContentBorderLeftStyle()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getContentBorderLeftStyle', []);

        return parent::getContentBorderLeftStyle();
    }

    /**
     * {@inheritDoc}
     */
    public function getContentBorderRightStyle()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getContentBorderRightStyle', []);

        return parent::getContentBorderRightStyle();
    }

    /**
     * {@inheritDoc}
     */
    public function getContentMarginTop()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getContentMarginTop', []);

        return parent::getContentMarginTop();
    }

    /**
     * {@inheritDoc}
     */
    public function getContentMarginBottom()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getContentMarginBottom', []);

        return parent::getContentMarginBottom();
    }

    /**
     * {@inheritDoc}
     */
    public function getContentMarginLeft()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getContentMarginLeft', []);

        return parent::getContentMarginLeft();
    }

    /**
     * {@inheritDoc}
     */
    public function getContentMarginRight()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getContentMarginRight', []);

        return parent::getContentMarginRight();
    }

    /**
     * {@inheritDoc}
     */
    public function setTitleHeight($titleHeight)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTitleHeight', [$titleHeight]);

        return parent::setTitleHeight($titleHeight);
    }

    /**
     * {@inheritDoc}
     */
    public function setTitleLineHeight($titleLineHeight)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTitleLineHeight', [$titleLineHeight]);

        return parent::setTitleLineHeight($titleLineHeight);
    }

    /**
     * {@inheritDoc}
     */
    public function setTitleBorderTopStyle($titleBorderTopStyle)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTitleBorderTopStyle', [$titleBorderTopStyle]);

        return parent::setTitleBorderTopStyle($titleBorderTopStyle);
    }

    /**
     * {@inheritDoc}
     */
    public function setTitleBorderBottomStyle($titleBorderBottomStyle)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTitleBorderBottomStyle', [$titleBorderBottomStyle]);

        return parent::setTitleBorderBottomStyle($titleBorderBottomStyle);
    }

    /**
     * {@inheritDoc}
     */
    public function setTitleBorderLeftStyle($titleBorderLeftStyle)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTitleBorderLeftStyle', [$titleBorderLeftStyle]);

        return parent::setTitleBorderLeftStyle($titleBorderLeftStyle);
    }

    /**
     * {@inheritDoc}
     */
    public function setTitleBorderRightStyle($titleBorderRightStyle)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTitleBorderRightStyle', [$titleBorderRightStyle]);

        return parent::setTitleBorderRightStyle($titleBorderRightStyle);
    }

    /**
     * {@inheritDoc}
     */
    public function setTitleMarginTop($titleMarginTop)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTitleMarginTop', [$titleMarginTop]);

        return parent::setTitleMarginTop($titleMarginTop);
    }

    /**
     * {@inheritDoc}
     */
    public function setTitleMarginBottom($titleMarginBottom)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTitleMarginBottom', [$titleMarginBottom]);

        return parent::setTitleMarginBottom($titleMarginBottom);
    }

    /**
     * {@inheritDoc}
     */
    public function setTitleMarginLeft($titleMarginLeft)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTitleMarginLeft', [$titleMarginLeft]);

        return parent::setTitleMarginLeft($titleMarginLeft);
    }

    /**
     * {@inheritDoc}
     */
    public function setTitleMarginRight($titleMarginRight)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTitleMarginRight', [$titleMarginRight]);

        return parent::setTitleMarginRight($titleMarginRight);
    }

    /**
     * {@inheritDoc}
     */
    public function setTitleIconMarginTop($titleIconMarginTop)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTitleIconMarginTop', [$titleIconMarginTop]);

        return parent::setTitleIconMarginTop($titleIconMarginTop);
    }

    /**
     * {@inheritDoc}
     */
    public function setTitleIconMarginBottom($titleIconMarginBottom)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTitleIconMarginBottom', [$titleIconMarginBottom]);

        return parent::setTitleIconMarginBottom($titleIconMarginBottom);
    }

    /**
     * {@inheritDoc}
     */
    public function setTitleIconMarginLeft($titleIconMarginLeft)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTitleIconMarginLeft', [$titleIconMarginLeft]);

        return parent::setTitleIconMarginLeft($titleIconMarginLeft);
    }

    /**
     * {@inheritDoc}
     */
    public function setTitleIconMarginRight($titleIconMarginRight)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTitleIconMarginRight', [$titleIconMarginRight]);

        return parent::setTitleIconMarginRight($titleIconMarginRight);
    }

    /**
     * {@inheritDoc}
     */
    public function setContentBorderTopStyle($contentBorderTopStyle)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setContentBorderTopStyle', [$contentBorderTopStyle]);

        return parent::setContentBorderTopStyle($contentBorderTopStyle);
    }

    /**
     * {@inheritDoc}
     */
    public function setContentBorderBottomStyle($contentBorderBottomStyle)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setContentBorderBottomStyle', [$contentBorderBottomStyle]);

        return parent::setContentBorderBottomStyle($contentBorderBottomStyle);
    }

    /**
     * {@inheritDoc}
     */
    public function setContentBorderLeftStyle($contentBorderLeftStyle)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setContentBorderLeftStyle', [$contentBorderLeftStyle]);

        return parent::setContentBorderLeftStyle($contentBorderLeftStyle);
    }

    /**
     * {@inheritDoc}
     */
    public function setContentBorderRightStyle($contentBorderRightStyle)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setContentBorderRightStyle', [$contentBorderRightStyle]);

        return parent::setContentBorderRightStyle($contentBorderRightStyle);
    }

    /**
     * {@inheritDoc}
     */
    public function setContentMarginTop($contentMarginTop)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setContentMarginTop', [$contentMarginTop]);

        return parent::setContentMarginTop($contentMarginTop);
    }

    /**
     * {@inheritDoc}
     */
    public function setContentMarginBottom($contentMarginBottom)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setContentMarginBottom', [$contentMarginBottom]);

        return parent::setContentMarginBottom($contentMarginBottom);
    }

    /**
     * {@inheritDoc}
     */
    public function setContentMarginLeft($contentMarginLeft)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setContentMarginLeft', [$contentMarginLeft]);

        return parent::setContentMarginLeft($contentMarginLeft);
    }

    /**
     * {@inheritDoc}
     */
    public function setContentMarginRight($contentMarginRight)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setContentMarginRight', [$contentMarginRight]);

        return parent::setContentMarginRight($contentMarginRight);
    }

    /**
     * {@inheritDoc}
     */
    public function applyDefaults()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'applyDefaults', []);

        return parent::applyDefaults();
    }

    /**
     * {@inheritDoc}
     */
    public function setPresetId($presetId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPresetId', [$presetId]);

        return parent::setPresetId($presetId);
    }

    /**
     * {@inheritDoc}
     */
    public function setPresetName($presetName)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPresetName', [$presetName]);

        return parent::setPresetName($presetName);
    }

    /**
     * {@inheritDoc}
     */
    public function setIsSystemPreset($isSystemPreset)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsSystemPreset', [$isSystemPreset]);

        return parent::setIsSystemPreset($isSystemPreset);
    }

    /**
     * {@inheritDoc}
     */
    public function setTitleBackgroundColorNormal($titleBackgroundColorNormal)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTitleBackgroundColorNormal', [$titleBackgroundColorNormal]);

        return parent::setTitleBackgroundColorNormal($titleBackgroundColorNormal);
    }

    /**
     * {@inheritDoc}
     */
    public function setTitleBackgroundColorHover($titleBackgroundColorHover)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTitleBackgroundColorHover', [$titleBackgroundColorHover]);

        return parent::setTitleBackgroundColorHover($titleBackgroundColorHover);
    }

    /**
     * {@inheritDoc}
     */
    public function setTitleBackgroundColorActive($titleBackgroundColorActive)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTitleBackgroundColorActive', [$titleBackgroundColorActive]);

        return parent::setTitleBackgroundColorActive($titleBackgroundColorActive);
    }

    /**
     * {@inheritDoc}
     */
    public function setTitleTextColorNormal($titleTextColorNormal)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTitleTextColorNormal', [$titleTextColorNormal]);

        return parent::setTitleTextColorNormal($titleTextColorNormal);
    }

    /**
     * {@inheritDoc}
     */
    public function setTitleTextColorHover($titleTextColorHover)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTitleTextColorHover', [$titleTextColorHover]);

        return parent::setTitleTextColorHover($titleTextColorHover);
    }

    /**
     * {@inheritDoc}
     */
    public function setTitleTextColorActive($titleTextColorActive)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTitleTextColorActive', [$titleTextColorActive]);

        return parent::setTitleTextColorActive($titleTextColorActive);
    }

    /**
     * {@inheritDoc}
     */
    public function setTitleTextFontWeight($titleTextFontWeight)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTitleTextFontWeight', [$titleTextFontWeight]);

        return parent::setTitleTextFontWeight($titleTextFontWeight);
    }

    /**
     * {@inheritDoc}
     */
    public function setTitleTextFontSize($titleTextFontSize)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTitleTextFontSize', [$titleTextFontSize]);

        return parent::setTitleTextFontSize($titleTextFontSize);
    }

    /**
     * {@inheritDoc}
     */
    public function setTitleTextDecoration($titleTextDecoration)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTitleTextDecoration', [$titleTextDecoration]);

        return parent::setTitleTextDecoration($titleTextDecoration);
    }

    /**
     * {@inheritDoc}
     */
    public function setTitleIconNormal($titleIconNormal)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTitleIconNormal', [$titleIconNormal]);

        return parent::setTitleIconNormal($titleIconNormal);
    }

    /**
     * {@inheritDoc}
     */
    public function setTitleIconActive($titleIconActive)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTitleIconActive', [$titleIconActive]);

        return parent::setTitleIconActive($titleIconActive);
    }

    /**
     * {@inheritDoc}
     */
    public function getOrientations()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOrientations', []);

        return parent::getOrientations();
    }

    /**
     * {@inheritDoc}
     */
    public function setTitleIconOrientation($titleIconOrientation)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTitleIconOrientation', [$titleIconOrientation]);

        return parent::setTitleIconOrientation($titleIconOrientation);
    }

    /**
     * {@inheritDoc}
     */
    public function setTitleIconPadding($titleIconPadding)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTitleIconPadding', [$titleIconPadding]);

        return parent::setTitleIconPadding($titleIconPadding);
    }

    /**
     * {@inheritDoc}
     */
    public function setTitleIconColorNormal($titleIconColorNormal)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTitleIconColorNormal', [$titleIconColorNormal]);

        return parent::setTitleIconColorNormal($titleIconColorNormal);
    }

    /**
     * {@inheritDoc}
     */
    public function setTitleIconBackgroundColorNormal($titleIconBackgroundColorNormal)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTitleIconBackgroundColorNormal', [$titleIconBackgroundColorNormal]);

        return parent::setTitleIconBackgroundColorNormal($titleIconBackgroundColorNormal);
    }

    /**
     * {@inheritDoc}
     */
    public function setTitleIconColorHover($titleIconColorHover)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTitleIconColorHover', [$titleIconColorHover]);

        return parent::setTitleIconColorHover($titleIconColorHover);
    }

    /**
     * {@inheritDoc}
     */
    public function setTitleIconBackgroundColorHover($titleIconBackgroundColorHover)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTitleIconBackgroundColorHover', [$titleIconBackgroundColorHover]);

        return parent::setTitleIconBackgroundColorHover($titleIconBackgroundColorHover);
    }

    /**
     * {@inheritDoc}
     */
    public function setTitleIconColorActive($titleIconColorActive)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTitleIconColorActive', [$titleIconColorActive]);

        return parent::setTitleIconColorActive($titleIconColorActive);
    }

    /**
     * {@inheritDoc}
     */
    public function setTitleIconBackgroundColorActive($titleIconBackgroundColorActive)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTitleIconBackgroundColorActive', [$titleIconBackgroundColorActive]);

        return parent::setTitleIconBackgroundColorActive($titleIconBackgroundColorActive);
    }

    /**
     * {@inheritDoc}
     */
    public function setTitleBorderBottomColor($titleBorderBottomColor)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTitleBorderBottomColor', [$titleBorderBottomColor]);

        return parent::setTitleBorderBottomColor($titleBorderBottomColor);
    }

    /**
     * {@inheritDoc}
     */
    public function setTitleBorderTopColor($titleBorderTopColor)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTitleBorderTopColor', [$titleBorderTopColor]);

        return parent::setTitleBorderTopColor($titleBorderTopColor);
    }

    /**
     * {@inheritDoc}
     */
    public function setTitleBorderLeftColor($titleBorderLeftColor)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTitleBorderLeftColor', [$titleBorderLeftColor]);

        return parent::setTitleBorderLeftColor($titleBorderLeftColor);
    }

    /**
     * {@inheritDoc}
     */
    public function setTitleBorderRightColor($titleBorderRightColor)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTitleBorderRightColor', [$titleBorderRightColor]);

        return parent::setTitleBorderRightColor($titleBorderRightColor);
    }

    /**
     * {@inheritDoc}
     */
    public function setTitleBorderBottomWidth($titleBorderBottomWidth)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTitleBorderBottomWidth', [$titleBorderBottomWidth]);

        return parent::setTitleBorderBottomWidth($titleBorderBottomWidth);
    }

    /**
     * {@inheritDoc}
     */
    public function setTitleBorderTopWidth($titleBorderTopWidth)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTitleBorderTopWidth', [$titleBorderTopWidth]);

        return parent::setTitleBorderTopWidth($titleBorderTopWidth);
    }

    /**
     * {@inheritDoc}
     */
    public function setTitleBorderLeftWidth($titleBorderLeftWidth)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTitleBorderLeftWidth', [$titleBorderLeftWidth]);

        return parent::setTitleBorderLeftWidth($titleBorderLeftWidth);
    }

    /**
     * {@inheritDoc}
     */
    public function setTitleBorderRightWidth($titleBorderRightWidth)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTitleBorderRightWidth', [$titleBorderRightWidth]);

        return parent::setTitleBorderRightWidth($titleBorderRightWidth);
    }

    /**
     * {@inheritDoc}
     */
    public function setTitlePaddingLeft($titlePaddingLeft)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTitlePaddingLeft', [$titlePaddingLeft]);

        return parent::setTitlePaddingLeft($titlePaddingLeft);
    }

    /**
     * {@inheritDoc}
     */
    public function setTitlePaddingRight($titlePaddingRight)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTitlePaddingRight', [$titlePaddingRight]);

        return parent::setTitlePaddingRight($titlePaddingRight);
    }

    /**
     * {@inheritDoc}
     */
    public function setTitlePaddingBottom($titlePaddingBottom)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTitlePaddingBottom', [$titlePaddingBottom]);

        return parent::setTitlePaddingBottom($titlePaddingBottom);
    }

    /**
     * {@inheritDoc}
     */
    public function setTitlePaddingTop($titlePaddingTop)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTitlePaddingTop', [$titlePaddingTop]);

        return parent::setTitlePaddingTop($titlePaddingTop);
    }

    /**
     * {@inheritDoc}
     */
    public function setContentBorderBottomColor($contentBorderBottomColor)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setContentBorderBottomColor', [$contentBorderBottomColor]);

        return parent::setContentBorderBottomColor($contentBorderBottomColor);
    }

    /**
     * {@inheritDoc}
     */
    public function setContentBorderTopColor($contentBorderTopColor)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setContentBorderTopColor', [$contentBorderTopColor]);

        return parent::setContentBorderTopColor($contentBorderTopColor);
    }

    /**
     * {@inheritDoc}
     */
    public function setContentBorderLeftColor($contentBorderLeftColor)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setContentBorderLeftColor', [$contentBorderLeftColor]);

        return parent::setContentBorderLeftColor($contentBorderLeftColor);
    }

    /**
     * {@inheritDoc}
     */
    public function setContentBorderRightColor($contentBorderRightColor)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setContentBorderRightColor', [$contentBorderRightColor]);

        return parent::setContentBorderRightColor($contentBorderRightColor);
    }

    /**
     * {@inheritDoc}
     */
    public function setContentBorderBottomWidth($contentBorderBottomWidth)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setContentBorderBottomWidth', [$contentBorderBottomWidth]);

        return parent::setContentBorderBottomWidth($contentBorderBottomWidth);
    }

    /**
     * {@inheritDoc}
     */
    public function setContentBorderTopWidth($contentBorderTopWidth)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setContentBorderTopWidth', [$contentBorderTopWidth]);

        return parent::setContentBorderTopWidth($contentBorderTopWidth);
    }

    /**
     * {@inheritDoc}
     */
    public function setContentBorderLeftWidth($contentBorderLeftWidth)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setContentBorderLeftWidth', [$contentBorderLeftWidth]);

        return parent::setContentBorderLeftWidth($contentBorderLeftWidth);
    }

    /**
     * {@inheritDoc}
     */
    public function setContentBorderRightWidth($contentBorderRightWidth)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setContentBorderRightWidth', [$contentBorderRightWidth]);

        return parent::setContentBorderRightWidth($contentBorderRightWidth);
    }

    /**
     * {@inheritDoc}
     */
    public function setContentPaddingLeft($contentPaddingLeft)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setContentPaddingLeft', [$contentPaddingLeft]);

        return parent::setContentPaddingLeft($contentPaddingLeft);
    }

    /**
     * {@inheritDoc}
     */
    public function setContentPaddingRight($contentPaddingRight)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setContentPaddingRight', [$contentPaddingRight]);

        return parent::setContentPaddingRight($contentPaddingRight);
    }

    /**
     * {@inheritDoc}
     */
    public function setContentPaddingBottom($contentPaddingBottom)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setContentPaddingBottom', [$contentPaddingBottom]);

        return parent::setContentPaddingBottom($contentPaddingBottom);
    }

    /**
     * {@inheritDoc}
     */
    public function setContentPaddingTop($contentPaddingTop)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setContentPaddingTop', [$contentPaddingTop]);

        return parent::setContentPaddingTop($contentPaddingTop);
    }

    /**
     * {@inheritDoc}
     */
    public function apply($arrSettings)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'apply', [$arrSettings]);

        return parent::apply($arrSettings);
    }

    /**
     * {@inheritDoc}
     */
    public function getLessVariables($returnAll = false)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLessVariables', [$returnAll]);

        return parent::getLessVariables($returnAll);
    }

    /**
     * {@inheritDoc}
     */
    public function getLessVariablesAsString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLessVariablesAsString', []);

        return parent::getLessVariablesAsString();
    }

    /**
     * {@inheritDoc}
     */
    public function getSettingsArray()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSettingsArray', []);

        return parent::getSettingsArray();
    }

    /**
     * {@inheritDoc}
     */
    public function remove()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'remove', []);

        return parent::remove();
    }

    /**
     * {@inheritDoc}
     */
    public function save($recompileCss = false)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'save', [$recompileCss]);

        return parent::save($recompileCss);
    }

    /**
     * {@inheritDoc}
     */
    public function export()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'export', []);

        return parent::export();
    }

}
