<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2024-01-05T15:48:34-06:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      recaptcha_v3.send_ip
 * @group     captcha
 * @namespace null
 * -----------------------------------------------------------------------------
 */
return [
    'recaptcha_v3' => [
        'site_key' => '6LdbrkcpAAAAAMIO6mkjitZanqp8oCDbtOvyGFYz',
        'secret_key' => '6LdbrkcpAAAAAIGq17PLqX4TY2wWD2lVRfj48BTk',
        'score' => 0.5,
        'position' => 'inline',
        'log_score' => false,
        'send_ip' => false,
    ],
];
