<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2025-03-27T11:59:20-05:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      cache.last_cleared
 * @group     concrete
 * @namespace null
 * -----------------------------------------------------------------------------
 */
return [
    'version_installed' => '9.2.1',
    'version_db_installed' => '20230503095900',
    'news_attribute_set_id' => '3',
    'news_page_type_id' => '7',
    'news_page_template_id' => '11',
    'misc' => [
        'login_redirect' => 'HOMEPAGE',
        'access_entity_updated' => 1706284738,
        'latest_version' => '9.2.2',
    ],
    'email' => [
        'default' => [
            'address' => 'developer@primeadvertising.com',
        ],
    ],
    'security' => [
        'production' => [
            'mode' => 'development',
        ],
        'misc' => [
            'content_security_policy' => true,
            'strict_transport_security' => true,
            'x_frame_options' => 'SAMEORIGIN',
        ],
        'trusted_proxies' => [
            'headers' => 0b001000,
            'ips' => [
                '173.245.48.0/20',
                '103.21.244.0/22',
                '103.22.200.0/22',
                '103.31.4.0/22',
                '141.101.64.0/18',
                '108.162.192.0/18',
                '190.93.240.0/20',
                '188.114.96.0/20',
                '197.234.240.0/22',
                '198.41.128.0/17',
                '162.158.0.0/15',
                '104.16.0.0/13',
                '104.24.0.0/14',
                '172.64.0.0/13',
                '131.0.72.0/22',
                '169.254.129.0/24',
                '169.254.131.0/24',
            ],
        ],
    ],
    'seo' => [
        'redirect_to_canonical_url' => true,
        'url_rewriting' => true,
    ],
    'cache' => [
        'blocks' => false,
        'assets' => false,
        'theme_css' => false,
        'overrides' => false,
        'pages' => '0',
        'full_page_lifetime' => 'custom',
        'full_page_lifetime_block' => false,
        'full_page_lifetime_value' => 2,
        'last_cleared' => 1743094760,
        'clear' => [
            'thumbnails' => true,
        ],
    ],
    'theme' => [
        'compress_preprocessor_output' => false,
        'generate_less_sourcemap' => false,
    ],
    'accessibility' => [
        'toolbar_titles' => true,
        'toolbar_tooltips' => true,
        'toolbar_large_font' => false,
    ],
    'file_manager' => [
        'images' => [
            'preview_image_size' => 'small',
            'preview_image_popover' => true,
        ],
    ],
];
