<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2025-02-19T15:20:43-06:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      sites.default.name
 * @group     site
 * @namespace null
 * -----------------------------------------------------------------------------
 */
return [
    'sites' => [
        'default' => [
            'name' => 'Connexus Energy',
            'timezone' => 'America/Chicago',
            'seo' => [
                'canonical_url' => 'https://dev.connexusenergy.com',
                'canonical_url_alternative' => 'https://dev.connexusenergy.com/',
                'canonical_tag' => [
                    'enabled' => true,
                ],
                'tracking' => [
                    'code' => [
                        'header' => '<!-- APG-ECM Publications Tracking tag. Place in the <body> section of webpage -->
<!-- Privacy policy at http://tag.brandcdn.com/privacy -->
<script type="text/javascript" src="//tag.brandcdn.com/autoscript/connexusenergy_vfdwtk0wouvvvda9/Connnexus_tag.js"></script>

<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-Z3CPPJNJ4H"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag(\'js\', new Date());

 gtag(\'config\', \'G-Z3CPPJNJ4H\', {
     \'cookie_flags\': \'SameSite=None;Secure\'
  });
</script>',
                        'footer' => '',
                    ],
                ],
            ],
            'misc' => [
                'favicon_fid' => 78,
                'iphone_home_screen_thumbnail_fid' => 77,
                'modern_tile_thumbnail_fid' => 76,
                'modern_tile_thumbnail_bgcolor' => null,
                'browser_toolbar_color' => null,
            ],
        ],
    ],
];
